#!/bin/sh
export PATH="/bin:/sbin:/usr/sbin:/usr/bin"

NEWGW=`netstat -nr | grep '^default' | grep -v 'ppp' | sed 's/default *\([0-9\.]*\) .*/\1/' | awk '{if($1){print $1}}'`
echo "$NEWGW" > /tmp/pptp_newgw
